Oneflow-Inc/models

scripts/compare_speed_with_pytorch.py

1. 输出 oneflow 对 pytorch 的相对速度
2. --time-only 改名成更准确的 --no-verbose

update speed script

---

.gitignore
FaceSeg/train.py
FaceSeg/validation_oneflow.py
FlappyBird/train.py
SRGAN/train_of_srgan.py
TSN/train_recognizer.py
alexnet/train.py
inception_v3/train.py
mobilenetv2/train.py
mobilenetv3/train.py
poseNet/train_oneflow.py
reid/reid.py
repvgg/train.py
resnet50/train_oneflow.py
resnext50_32x4d/train.py
rnn/train_lstm_oneflow.py
rnn/train_rnn_oneflow.py
scnet/train_oneflow.py
shufflenetv2/train.py
vgg/train_oneflow.py

由于0-dim tensor的支持，导致获取loss的numpy数据时接口有变化，这里fix一下，另外gitignore里面加入了一些常用的可能会误传的文件以及文件夹。

fix 0-dim tensor's bug

---

bert-oneflow/model/bert.py
bert-oneflow/model/embedding/bert.py
bert-oneflow/trainer/pretrain.py

Bert quick fix

---

DCGAN/models.py
alexnet/check/check.py
alexnet/graph/train.py
resnet50/check/check.py
resnet50/graph/train.py

oneflow master merge 了 https://github.com/Oneflow-Inc/oneflow/pull/5846

rm add_optimizer name

---

scripts/compare_speed_with_pytorch.py

compare_speed_with_pytorch.py 增加和 pytorch 对比 ddp 速度的功能，用法示例：
```bash
python3 -m oneflow.distributed.launch --nproc_per_node 2 scripts/compare_speed_with_pytorch.py resnet50/models/resnet50.py resnet50 1x3x224x224 --ddp
```

add --ddp in compare_speed_with_pytorch.py

---

fast_neural_style/neural_style/neural_style.py
fast_neural_style/neural_style/utils.py

1. 删除不必要的import
2. 修改reshape入参
3. 去除numpy()[0]的索引[0]

fix fast_neural_style bug

---

pix2pix/infer.sh
pix2pix/train.py
pix2pix/train.sh

1. 替换python为python3
2. .numpy()[0]去掉索引[0]

fix pix2pix_bugfix bug

---

rnn/models/lstm_oneflow.py
seq2seq/eval_oneflow.py
seq2seq/eval_oneflow.sh
seq2seq/models/seq_seq_oneflow.py
seq2seq/train_oneflow.py
seq2seq/train_oneflow.sh
seq2seq/utils/utils_oneflow.py

由于这个项目是我在很早以前的版本写的，所以运行出了点问题，修改后可以正常跑通。

refine the seq2seq

---

mobilenetv2/infer.sh
mobilenetv2/train.py
mobilenetv2/train.sh

fix mobilenetv2

---

SincNet/infer.sh
SincNet/model/dnn_models.py
densenet/train.py
seq2seq/eval_oneflow.py
seq2seq/models/seq_seq_oneflow.py

convert flow.F to flow.nn.functional

fix some issues

---

CSRNet/infer.py
CSRNet/infer.sh
CSRNet/train.py
CSRNet/train.sh
CSRNet/val.py
CSRNet/val.sh
CSRNet/vgg.py

本次PR解决的问题是
- debug CSRNet train
- debug CSRNet val 
- debug CSRNet infer
- 重新上传权重数据集

fix CSRNet train infer val

---

DCGAN/check/check.sh
DCGAN/eager/train.py
DCGAN/models.py
DCGAN/test/test_of_dcgan.sh
SRGAN/requirements.txt
SRGAN/train_of_srgan.py

主要修复： 
1. reshape传参问题
2. shell脚本路径问题
3. 训练中导入不存在的权重

Fix Bug in GAN

---

Wav2Letter/Wav2Letter/decoder.py
Wav2Letter/infer.py
Wav2Letter/requirements.txt
Wav2Letter/train.py
Wav2Letter/train.sh
scripts/compare_speed_with_pytorch.py

fix some error

---

CSRNet/vgg.py
DLA/README.md
DLA/requirements.txt
DLA/train_oneflow.py
DLA/train_oneflow.sh
seq2seq/eval_oneflow.py

1. 删除visdom相关的包
2. 修改readme
3. 修复.numpy()[0]多余索引[0]

Dla bugfix

---

TSN/tsn/models/TSN.py
TSN/tsn/models/cls_head.py

fix bug in TSN

---

resnet50/utils/logger.py

**refine resnet50 logger，add timestamp**
```shell
[1] [train], epoch: 0/50, iter: 100/3336, loss: 1.73143, lr: 0.004604, top1: 0.00167, throughput: 161.66
[0] [train], epoch: 0/50, iter: 100/3336, loss: 1.73064, lr: 0.004604, top1: 0.00208, throughput: 159.71
[3] [train], epoch: 0/50, iter: 100/3336, loss: 1.73078, lr: 0.004604, top1: 0.00167, throughput: 159.48
[2] [train], epoch: 0/50, iter: 100/3336, loss: 1.73150, lr: 0.004604, top1: 0.00146, throughput: 159.49
```

add logger timestamp

---

docs/requirements.txt

Finish Docs in OneFlow-Models

---

NLP/CPT/infer.sh

small bug in infer.sh

---

README_zh-CN.md

update CN documents

---

Vision/classification/image/ViT/eager/infer.py
Vision/classification/image/ViT/eager/train.py

fix error name

---

Vision/classification/image/mnasnet/eager/infer.sh
Vision/classification/image/mnasnet/eager/train.sh
Vision/classification/image/mnasnet/graph/infer.py
Vision/classification/image/mnasnet/graph/infer.sh
Vision/classification/image/mnasnet/graph/train.sh

fix mnasnet error

---

Vision/oneflow_face/function.py
Vision/oneflow_face/graph.py
Vision/oneflow_face/utils/utils_callbacks.py
Vision/oneflow_face/val.py

fix path errors

---

Vision/classification/image/resnet50/models/resnet50.py

fix resnet50

---

Vision/classification/image/resnet50/graph.py

等 https://github.com/Oneflow-Inc/oneflow/pull/6799 合并后合并此pr

set enable_cudnn_conv_heuristic_search_algo

---

RecommenderSystems/wide_and_deep/README.md

add dataset preparation for wide and deep.

udpate wdl readme for data preparation

---

RecommenderSystems/dlrm/config.py
RecommenderSystems/dlrm/models/dlrm.py
RecommenderSystems/dlrm/train.py

support embedding model parallel along axis 0 or 1.

Dev dlrm embedding split

---

Vision/classification/image/resnet50/models/data.py
Vision/classification/image/resnet50/train.py

consistent 相关接口名称改动，consistent改成global：
- consistent_id
- consistent_arange
- consistent_constant
- consistent_empty
- consistent_all_reduce
- consistent_reduce_scatter
- consistent_all_gather
- consistent_s2s
- local_to_consistent
- to_consistent

change is_consistent to is_global, to_consistent to to_global

---

.gitignore
scripts/swin_dataloader_compare_speed_with_pytorch.py

swin dataloader speed test in oneflow ci

---

RecommenderSystems/dlrm/README.md
RecommenderSystems/dlrm/dlrm_train_eval.py
RecommenderSystems/dlrm/tools/criteo1t_parquet.py

- eval dataload pipeline
- keep local predictions on every step, to_global at last

Update dlrm eval

---

RecommenderSystems/dlrm/tools/criteo1t_parquet.scala
RecommenderSystems/dlrm/tools/split_day_23.sh

update dlrm tool default path

---

RecommenderSystems/dcn/dcn_train_eval.py
RecommenderSystems/dlrm/dlrm_train_eval.py
RecommenderSystems/mmoe/mmoe_train_eval.py
RecommenderSystems/pnn/pnn_train_eval.py

make_table -> make_table_options

make_table_options

---

RecommenderSystems/dlrm/README.md
RecommenderSystems/dlrm/tools/criteo1t_parquet_day_by_day.scala

make DLRM parquet dataset day by day with limited resources( CPU memory 64G)

Make dlrm ds dbd

---

RecommenderSystems/dlrm/README.md
RecommenderSystems/dlrm/tools/criteo1t_parquet_day_by_day.scala

Fix dlrm scala tool
